### ISSUE TITLE
If you put in the wrong team. eg I tried hmcts/dts (rather than say hmcts/reform) Non descript failure occurred

### ISSUE THREAD

**Issue by rajivkapoor1** [hmcts/golden-path-java#14]
### What would you like to change?

More informational failure. I tried with team as hmcts/dts (which I think doesnt exist), and I got the following error...Upon trying to Create the Spring Boot code using the template. The below (current) error is not very helpful for example...

2022-02-11T09:40:22.375Z Beginning step Publish
2022-02-11T09:40:27.813Z HttpError: Not Found
    at /usr/src/app/node_modules/@octokit/request/dist-node/index.js:86:21
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at async Object.handler (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:1300:9)
    at async NunjucksWorkflowRunner.execute (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2446:11)
    at async TaskWorker.runOneTask (/usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2527:85)
    at async /usr/src/app/node_modules/@backstage/plugin-scaffolder-backend/dist/index.cjs.js:2521:9

### How do you think that would improve the project?

AS the project is typically for new starters, it would be helpful to have more informational failures...

**Comment by timja** [comment]
Thanks for the feedback!

This is likely an upstream issue but I'll check it when we next update backstage and report it upstream if it's not fixed.
